gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  # showIcons: true
  language: "en"
git:
  log:
    showGraph: always
os:
  edit: nvim --server /tmp/nvim.pipe --remote-tab "$(pwd)/{{filename}}"
  editInTerminal: false
