gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  language: "en"
git:
  log:
    showGraph: always
os:
  editPreset: "nvim-remote"
disableStartupPopups: true
notARepository: "quit" # one of: 'prompt' | 'create' | 'skip' | 'quit'
promptToReturnFromSubprocess: false
